Importing dependencies

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

Importing dtaset

In [2]:
data = pd.read_csv("../files/nova_pay_transcations (1).csv")

In [3]:
# creating a check point
df = data.copy()

In [4]:
# view first 5 rows
df.head()

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
0,fee8542d-8ee6-4b0d-9671-c294dd08ed26,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-03 18:40:59.468549+00:00,US,USD,CAD,ATM,278.19,278.19,4.25,...,0.123,standard,263,0.522,0,0.223,0,0,0.0,0
1,bfdb9fc1-27fe-4a85-b043-4d813d679259,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-10-03 20:39:38.468549+00:00,CA,CAD,MXN,web,208.51,154.29,4.24,...,0.569,standard,947,0.475,0,0.268,0,1,0.0,0
2,fc855034-3ea5-4993-9afa-b511d93fe5e8,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-03 23:02:43.468549+00:00,US,USD,CNY,mobile,160.33,160.33,2.70,...,0.437,enhanced,367,0.939,0,0.176,0,0,0.0,0
3,2cf8c08e-42ec-444d-a755-34b9a2a0a4ca,7bd5200c-5d19-44f0-9afe-8b339a05366b,2022-10-04 01:08:53.468549+00:00,US,USD,EUR,mobile,59.41,59.41,2.22,...,0.594,standard,147,0.551,0,0.391,0,0,0.0,0
4,d907a74d-b426-438d-97eb-dbe911aca91c,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-10-04 09:35:03.468549+00:00,US,USD,INR,mobile,200.96,200.96,3.61,...,0.121,enhanced,257,0.894,0,0.257,0,0,0.0,0

In [5]:
# shape
df.shape

(10200, 26)

In [6]:
# checking for duplicates
df.duplicated().sum()

200

In [7]:
# Reviewing duplicated rows to check for validity
duplicates = df[df.duplicated(keep = False)]

duplicates.head(20)

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,ip_risk_score,kyc_tier,account_age_days,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud
57,4662cb2d-21b2-4390-ba38-5a1eddebdc7c,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-09 20:21:25.468549+00:00,US,USD,GBP,mobile,152.75,152.75,3.35,...,0.328,standard,263,0.522,0,0.223,5,5,0.00,0
83,e69d481f-2ee3-4621-a58a-73fec8c63eca,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-13 03:17:46.468549+00:00,US,USD,CNY,ATM,385.27,385.27,7.05,...,0.458,enhanced,367,0.939,0,0.176,0,0,0.00,0
178,8537371a-7eae-4108-89c9-5660e5025a88,d71c91b4-fee8-4104-9856-a5c6109a62e3,2022-10-23 16:36:46.468549+00:00,US,USD,MXN,web,86.6,86.60,1.96,...,0.342,standard,298,0.336,0,0.166,0,0,0.20,0
245,2e553c23-063e-4b5e-aa2e-8a41d6aa61ca,0f5daa28-9086-4c15-8379-eb7a440393c7,2022-10-30 19:05:06.468549+00:00,UK,GBP,EUR,web,165.39,206.73,4.07,...,0.200,standard,281,0.704,0,0.522,0,0,0.05,0
352,a9198fb0-d831-48df-b434-c30a39078aa3,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-11-13 04:59:47.468549+00:00,US,USD,CNY,web,85.68,85.68,1.91,...,0.601,standard,263,0.522,0,0.223,0,0,0.00,0
396,22566dff-8c67-4119-9d2d-fa23862199c8,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-11-17 23:09:01.468549+00:00,CA,CAD,MXN,mobile,207.23,153.35,3.73,...,0.340,standard,947,0.625,0,0.268,0,0,0.00,0
462,a5c6391d-4763-4ed6-a5ef-80b744cf71b2,af8ca4c4-8703-4c55-b66c-2b76cd70040d,2022-11-25 16:25:46.468549+00:00,US,USD,GBP,mobile,127.91,127.91,2.97,...,0.315,standard,1018,0.934,0,0.087,0,0,0.00,0
464,d111a38d-879a-4354-9666-82ce420b9f4a,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-11-25 20:26:14.468549+00:00,US,USD,USD,web,237.21,237.21,3.55,...,0.587,enhanced,257,0.894,0,0.257,0,0,0.00,0
626,4c80a822-dda8-46e0-a5f5-a621a24210b8,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-12-14 21:03:21.468549+00:00,US,USD,USD,mobile,322.33,322.33,5.13,...,0.166,enhanced,257,0.894,0,0.257,0,0,0.00,0
713,e952671a-33bc-4c98-9242-f47caad7741c,d71c91b4-fee8-4104-9856-a5c6109a62e3,2022-12-23 11:34:47.468549+00:00,US,USD,GBP,web,109.46,109.46,2.73,...,0.173,standard,298,0.336,0,0.166,0,0,0.00,0
754,c0059f95-5daa-415b-b686-924d3ee4ca9b,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-12-27 14:57:57.468549+00:00,US,USD,NGN,mobile,281.66,281.66,5.05,...,0.270,enhanced,367,0.939,0,0.176,0,0,0.25,0
783,88b5e91e-c9ba-4a58-b18f-a234a7a03cc8,23d9943d-57b1-42eb-9ef2-05eed7fd1957,2022-12-31 03:48:28.468549+00:00,UK,GBP,PHP,mobile,121.2,151.50,2.56,...,0.410,standard,718,0.953,0,0.169,0,1,0.00,0
798,883403f5-fd2f-4b39-824e-9710485a983e,7041b9c1-3719-4ca8-9a6b-811b47cea6c0,2023-01-01 02:40:14.468549+00:00,UK,GBP,PHP,mobile,-168.96,211.20,9999.99,...,1.200,standard,4,-0.100,0,0.407,-1,0,0.00,0
906,a71aaac9-2819-4f46-9ec9-1f2699ecc2aa,d71c91b4-fee8-4104-9856-a5c6109a62e3,2023-01-13 08:21:54.468549+00:00,US,USD,NGN,mobile,703.7,703.70,11.71,...,0.251,standard,298,0.336,0,0.166,0,0,0.25,0
912,35c133e7-7279-4d24-ac0e-967675f2c2a0,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2023-01-13 16:50:48.468549+00:00,US,USD,CNY,ATM,286.59,286.59,5.12,...,0.383,enhanced,257,0.894,0,0.257,0,0,0.00,0
919,40049bb9-944d-4add-8f1f-06c2732e8a9d,402cccc9-28de-45b3-9af7-cc5302aa1f93,2023-01-14 04:24:49.468549+00:00,US,USD,USD,ATM,140.01,140.01,3.68,...,0.235,standard,263,0.522,0,0.223,0,0,0.00,0
1143,f70c112d-9406-4ac9-b1fd-d31f4d972e0e,402cccc9-28de-45b3-9af7-cc5302aa1f93,2023-02-08 02:13:40.468549+00:00,US,USD,CNY,mobile,214.19,214.19,3.99,...,0.246,standard,263,0.522,0,0.223,0,0,0.00,0
1172,1174a4a4-d11e-423f-b212-c70a2986df4e,d71c91b4-fee8-4104-9856-a5c6109a62e3,2023-02-09 20:10:30.468549+00:00,US,USD,EUR,mobile,96.54,96.54,2.16,...,1.000,standard,298,0.336,0,0.166,0,0,0.00,0
1273,a96e7cc8-8d34-464d-8d93-b0dab38db30b,af8ca4c4-8703-4c55-b66c-2b76cd70040d,2023-02-20 05:52:56.468549+00:00,US,USD,CNY,web,181.18,181.18,3.22,...,0.424,standard,1018,0.934,0,0.087,0,0,0.00,0
1289,41ffc5f6-a17e-4a3e-97be-be4cf7f38860,66c71a44-d07c-4a20-a576-0a377193bf6b,2023-02-22 02:22:59.468549+00:00,US,USD,PHP,mobile,83.8,83.80,1.32,...,0.096,standard,34,0.427,0,0.068,0,0,0.10,0

Remove Technical Duplicates

These are rows that are identical in every single way. They usually happen due to system glitches during data export. You must remove these first to prevent data leakage.

In [8]:
df = df.drop_duplicates(keep='first')

print(f"Shape after removing exact duplicates: {df.shape}")

Shape after removing exact duplicates: (10000, 26)

In [9]:
# Getting the entire dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   transaction_id             10000 non-null  object
 1   customer_id                10000 non-null  object
 2   timestamp                  9971 non-null   object
 3   home_country               10000 non-null  object
 4   source_currency            10000 non-null  object
 5   dest_currency              10000 non-null  object
 6   channel                    10000 non-null  object
 7   amount_src                 10000 non-null  object
 8   amount_usd                 9700 non-null   float64
 9   fee                        9710 non-null   float64
 10  exchange_rate_src_to_dest  10000 non-null  float64
 11  device_id                  10000 non-null  object
 12  new_device                 10000 non-null  bool
 13  ip_address                 9700 non-null   object
 14  ip_country                 9704 non-null   object
 15  location_mismatch          10000 non-null  bool
 16  ip_risk_score              10000 non-null  float64
 17  kyc_tier                   9705 non-null   object
 18  account_age_days           10000 non-null  int64
 19  device_trust_score         9710 non-null   float64
 20  chargeback_history_count   10000 non-null  int64
 21  risk_score_internal        10000 non-null  float64
 22  txn_velocity_1h            10000 non-null  int64
 23  txn_velocity_24h           10000 non-null  int64
 24  corridor_risk              10000 non-null  float64
 25  is_fraud                   10000 non-null  int64
dtypes: bool(2), float64(7), int64(5), object(12)
memory usage: 1.9+ MB

Handling Data Types

In [10]:
# Converting to datetime and extract features
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

In [11]:
# Converting amount_src to Numeric
df['amount_src'] = (
    df['amount_src']
    .replace(r'[^\d.]', '', regex=True)
    .astype(float)
)

In [12]:
# Ensuring booleans are 1/0 for the model
df['new_device'] = df['new_device'].astype(int)
df['location_mismatch'] = df['location_mismatch'].astype(int)

 Handle Timestamps

In [13]:
# Filling missing timestamps with the median to avoid dropping data
df['timestamp'] = df['timestamp'].fillna(df['timestamp'].median())

df['hour_of_day'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek
df['is_weekend'] = df['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

Clean Numeric Fields

In [14]:
# Impute missing amount_usd using amount_src * exchange_rate where possible
mask = df['amount_usd'].isnull()
df.loc[mask, 'amount_usd'] = df.loc[mask, 'amount_src'] * df.loc[mask, 
                                                                 'exchange_rate_src_to_dest']

In [15]:
# Filling remaining nulls in fee and trust scores with medians
df['fee'] = df['fee'].fillna(df['fee'].median())
df['device_trust_score'] = df['device_trust_score'].fillna(df['device_trust_score'].median())

Categorical Columns

In [16]:
# kyc
df['kyc_tier'].unique()

array(['standard', 'enhanced', 'low', ' standard  ', nan, 'standrd',
       ' enhanced  ', 'STANDARD', 'NAN', 'unknown', 'enhancd', ' low  ',
       'ENHANCED', 'LOW', ' nan  '], dtype=object)

In [17]:
# Standardizing casing and removing leading/trailing whitespace
df['kyc_tier'] = df['kyc_tier'].astype(str).str.strip().str.lower()

# Defining a clean mapping for misspellings and redundant labels
kyc_mapping = {
    'standrd': 'standard',
    'enhancd': 'enhanced',
    'nan': 'unknown',
    'none': 'unknown',
    'n/a': 'unknown'
}

# Applying the mapping
df['kyc_tier'] = df['kyc_tier'].replace(kyc_mapping)

# Handling actual NaN values
df['kyc_tier'] = df['kyc_tier'].replace('nan', 'unknown')
df['kyc_tier'] = df['kyc_tier'].fillna('unknown')

# Final validation
print(f"Cleaned KYC Tiers: {df['kyc_tier'].unique()}")

Cleaned KYC Tiers: ['standard' 'enhanced' 'low' 'unknown']

In [18]:
# channel
df['channel'].unique()

array(['ATM', 'web', 'mobile', 'WEB', ' web  ', 'MOBILE', 'mobille',
       'unknown', ' mobile  ', 'weeb', 'ATm', ' ATM  '], dtype=object)

In [19]:
# Stripping whitespace and converting to lowercase
df['channel'] = df['channel'].str.strip().str.lower()

# Defining a mapping for misspellings and variations
channel_mapping = {
    'weeb': 'web',
    'mobille': 'mobile',
    'atm': 'atm',
    'unknown': 'other'
}

# Applying the mapping
df['channel'] = df['channel'].replace(channel_mapping)

# Verifying the fix
print(f"Cleaned Channels: {df['channel'].unique()}")

Cleaned Channels: ['atm' 'web' 'mobile' 'other']

In [20]:
# home country
df['home_country'].unique()

array(['US', 'CA', 'UK', ' UK  ', ' US  ', 'unknown', ' CA  '],
      dtype=object)

In [21]:
# Casting to string, removing whitespace, and converting to uppercase for ISO consistency
df['home_country'] = df['home_country'].astype(str).str.strip().str.upper()

# Mapping all variants of 'nan' and 'none' to a standard 'UNKNOWN'
df['home_country'] = df['home_country'].replace(['NAN', 'NONE', 'NULL'], 'UNKNOWN')

# Final validation
print(f"Unique values in home_country: {df['home_country'].unique()}")

Unique values in home_country: ['US' 'CA' 'UK' 'UNKNOWN']

In [30]:
# ip_country
df['ip_country'].unique()

array(['US', 'CA', nan, 'UK', ' US  ', 'NAN', 'unknown', ' CA  ', ' UK  ',
       ' nan  '], dtype=object)

In [31]:
# String conversion, strip whitespace, and Uppercase
df['ip_country'] = df['ip_country'].astype(str).str.strip().str.upper()

# Consolidate Nulls: Map variants to 'UNKNOWN'
df['ip_country'] = df['ip_country'].replace(['NAN', 'NONE', 'NULL'], 'UNKNOWN')

# 3. Final Validation
print(f"Unique values in ip_country: {df['ip_country'].unique()}")

Unique values in ip_country: ['US' 'CA' 'UNKNOWN' 'UK']

In [32]:
# source currency
df['source_currency'].unique()

array(['USD', 'CAD', 'GBP'], dtype=object)

In [33]:
df['dest_currency'].unique()

array(['CAD', 'MXN', 'CNY', 'EUR', 'INR', 'GBP', 'PHP', 'NGN', 'USD'],
      dtype=object)

In [34]:
# verifying
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   transaction_id             10000 non-null  object
 1   customer_id                10000 non-null  object
 2   timestamp                  10000 non-null  datetime64[ns, UTC]
 3   home_country               10000 non-null  object
 4   source_currency            10000 non-null  object
 5   dest_currency              10000 non-null  object
 6   channel                    10000 non-null  object
 7   amount_src                 10000 non-null  float64
 8   amount_usd                 10000 non-null  float64
 9   fee                        10000 non-null  float64
 10  exchange_rate_src_to_dest  10000 non-null  float64
 11  device_id                  10000 non-null  object
 12  new_device                 10000 non-null  int32
 13  ip_address                 9700 non-null   object
 14  ip_country                 10000 non-null  object
 15  location_mismatch          10000 non-null  int32
 16  ip_risk_score              10000 non-null  float64
 17  kyc_tier                   10000 non-null  object
 18  account_age_days           10000 non-null  int64
 19  device_trust_score         10000 non-null  float64
 20  chargeback_history_count   10000 non-null  int64
 21  risk_score_internal        10000 non-null  float64
 22  txn_velocity_1h            10000 non-null  int64
 23  txn_velocity_24h           10000 non-null  int64
 24  corridor_risk              10000 non-null  float64
 25  is_fraud                   10000 non-null  int64
 26  hour_of_day                10000 non-null  int32
 27  day_of_week                10000 non-null  int32
 28  is_weekend                 10000 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(8), int32(4), int64(6), object(10)
memory usage: 2.1+ MB

In [35]:
df_cleaned = df.copy()

In [36]:
df_cleaned.head()

,transaction_id,customer_id,timestamp,home_country,source_currency,dest_currency,channel,amount_src,amount_usd,fee,...,device_trust_score,chargeback_history_count,risk_score_internal,txn_velocity_1h,txn_velocity_24h,corridor_risk,is_fraud,hour_of_day,day_of_week,is_weekend
0,fee8542d-8ee6-4b0d-9671-c294dd08ed26,402cccc9-28de-45b3-9af7-cc5302aa1f93,2022-10-03 18:40:59.468549+00:00,US,USD,CAD,atm,278.19,278.19,4.25,...,0.522,0,0.223,0,0,0.0,0,18,0,0
1,bfdb9fc1-27fe-4a85-b043-4d813d679259,67c2c6b3-ef0a-4777-a3f1-c84a851bb6ad,2022-10-03 20:39:38.468549+00:00,CA,CAD,MXN,web,208.51,154.29,4.24,...,0.475,0,0.268,0,1,0.0,0,20,0,0
2,fc855034-3ea5-4993-9afa-b511d93fe5e8,6d0d9b27-fa26-45f8-93b1-2df29d182d9c,2022-10-03 23:02:43.468549+00:00,US,USD,CNY,mobile,160.33,160.33,2.70,...,0.939,0,0.176,0,0,0.0,0,23,0,0
3,2cf8c08e-42ec-444d-a755-34b9a2a0a4ca,7bd5200c-5d19-44f0-9afe-8b339a05366b,2022-10-04 01:08:53.468549+00:00,US,USD,EUR,mobile,59.41,59.41,2.22,...,0.551,0,0.391,0,0,0.0,0,1,1,0
4,d907a74d-b426-438d-97eb-dbe911aca91c,70a93d26-8e3a-4179-900c-a4a7a74d08e5,2022-10-04 09:35:03.468549+00:00,US,USD,INR,mobile,200.96,200.96,3.61,...,0.894,0,0.257,0,0,0.0,0,9,1,0

In [37]:
# Save for the next steps
df_cleaned.to_csv('../files/nova_pay_cleaned.csv', index=False)
print("Data Cleaning Complete. Shape:", df_cleaned.shape)

Data Cleaning Complete. Shape: (10000, 29)